Repository Atharva-cyber-dark/Portfolio-website-, pull requests merged in 2022-10, with the labels that each got.

#7 Create indexhome.html
  indexhome.html
Labels: enhancement, hacktoberfest-accepted

#8 Create index.html
  Footer/index.html
Labels: enhancement, help wanted, hacktoberfest-accepted

#9 Create style.css
  Footer/style.css
Labels: documentation, enhancement, hacktoberfest-accepted

#11 Added Footer
  Footer/index.html
  Footer/style.css
  login form/index.html
  login form/style.css
Labels: documentation, enhancement, hacktoberfest-accepted

#12 Create index.html
  AAMAN folder/index.html
  AAMAN folder/style.css
Labels: documentation, hacktoberfest-accepted

#13 Create index.js
  AAMAN folder/index.js
Labels: documentation, hacktoberfest-accepted

#14 Create Contact_me.html
  Contact_me.html
Labels: hacktoberfest-accepted

#15 Create Dark_Mode_Button.html
  Dark_Mode_Button.html
Labels: enhancement, hacktoberfest-accepted

#16 Html code for web page
  index1.html
  style1.css
Labels: documentation, hacktoberfest-accepted

#17 search bar for a website
  search bar.html
Labels: hacktoberfest-accepted

#18 Add files via upload
  umang_badhwar_portfolio/portfolio.css
  umang_badhwar_portfolio/portfolio.html
Labels: documentation, enhancement, hacktoberfest-accepted

#21 Create loadinganimation.html
  .vscode/loadinganimation.html
Labels: hacktoberfest-accepted

#20 Create loadinganimation.css
  .vscode/loadinganimation.css
Labels: hacktoberfest-accepted

#19 Create loadinganimation.js
  .vscode/loadinganimation.js
Labels: hacktoberfest-accepted

#24 Skill page
  Ekta/Footer/index.html
  Ekta/Footer/style.css
  Ekta/Skill Page/index.html
  Ekta/Skill Page/style.css
  Ekta/assets/images/1200px-HTML5_logo_and_wordmark.svg.png
  Ekta/assets/images/1200px-Vue.js_Logo_2.svg.png
  Ekta/assets/images/Angular_full_color_logo.svg.png
  Ekta/assets/images/CSS3_logo_and_wordmark.svg.png
  Ekta/assets/images/Facebook_f_logo_(2021).svg.png
  Ekta/assets/images/ISO_C++_Logo.svg.png
  Ekta/assets/images/Instagram_logo_2022.svg.webp
  Ekta/assets/images/React-icon.svg.png
  Ekta/assets/images/Twitter-logo.svg.png
  Ekta/assets/images/Unofficial_JavaScript_logo_2.svg.png
  Ekta/assets/images/github.svg
  Ekta/assets/images/linkedin.png
Labels: enhancement, hacktoberfest-accepted

#22 Made a docker File for the webapp
  AAMAN folder/docker.txt
Labels: hacktoberfest-accepted
